#!/usr/bin/env Rscript

# Load libraries
library(dplyr)
library(MetBrewer)
require(ggplot2)

# This section creates the figures (S9-S10) using data
# from "Final_combined_all_sites_geno_information_MAF_threshold.csv"
# which was generated by the script: Concordance_FPR_FNR_calculations_MAF_threshold.r

# Read the dataset from the CSV file
val.GP.sample<-data.frame(read.csv("Final_combined_all_sites_geno_information_MAF_threshold.csv"))

# Convert the 'COVERAGE' and 'N' columns to numeric
val.GP.sample$COVERAGE <- as.numeric(val.GP.sample$COVERAGE)
val.GP.sample$N <- as.numeric(val.GP.sample$N)

# Filter the dataset to include only heterozygous and homozygous alternative genotypes
val.GP.sample_het_homo_alt <- val.GP.sample[val.GP.sample$SAMPLE %in% c("0/1","1/1"),]
val.GP.sample_het_homo_alt$N <- as.numeric(val.GP.sample_het_homo_alt$N)

# Aggregate the counts of genotypes by dataset, coverage, and name
val.GP.sample_het_homo_alt_total <- aggregate(cbind(N) ~ DATASET + COVERAGE + NAME, data = val.GP.sample_het_homo_alt, sum)
val.GP.sample_total <- aggregate(cbind(N) ~ DATASET + COVERAGE + NAME, data = val.GP.sample, sum)

# Define color palette and shapes for the plots
pal<- met.brewer(name="Greek",n=5,type="discrete")
shapes <- c(2,1,0)

# Create plots
pdf("Number_of_sites_het_homo_alt_sep_0.1-4x_nomissing.pdf",width = 6, height = 1.5)
ggplot(data=val.GP.sample_het_homo_alt,aes(x=COVERAGE,y=N,colour=as.character(DATASET))) +
  geom_line(linewidth=0.5,aes(linetype=SAMPLE)) + scale_linetype_manual(values=c("solid","dotted")) + 
  theme_bw(base_size=7) + scale_colour_manual(values = pal) + xlim(c(0.1,4)) + facet_wrap(~NAME, ncol=4) +
  labs(color='Minimum GP', shape= 'Genotypes') + ylab("Number of imputed sites") 
dev.off()

pdf("Number_of_sites_het_homo_alt_total_0.1-4x_nomissing.pdf",width = 6, height = 1.5)
ggplot(data=val.GP.sample_total,aes(x=COVERAGE,y=N,colour=as.character(DATASET))) + 
  geom_line(linewidth=0.5) + theme_bw(base_size=7)  + scale_colour_manual(values = pal) + xlim(c(0.1,4)) +
  facet_wrap(~NAME, ncol=4) + labs(color='Minimum GP') + ylab("Number Heterozygous + Homozygous alternative imputed sites") 
dev.off()

pdf("Number_of_sites_het_homo_alt_sep_0.1-1x_nomissing.pdf",width = 6, height = 1.5)
ggplot(data=val.GP.sample_het_homo_alt,aes(x=COVERAGE,y=N,colour=as.character(DATASET))) +
  geom_line(linewidth=0.5,aes(linetype=SAMPLE)) + scale_linetype_manual(values=c("solid","dotted")) +
  theme_bw(base_size=7) + scale_colour_manual(values = pal) + xlim(c(0.1,1)) + facet_wrap(~NAME, ncol=4) + 
  labs(color='Minimum GP', shape= 'Genotypes') + ylab("Number of imputed sites") 
dev.off()

pdf("Number_of_sites_het_homo_alt_total_0.1-1x_nomissing.pdf",width = 6, height = 1.5)
ggplot(data=val.GP.sample_total,aes(x=COVERAGE,y=N,colour=as.character(DATASET))) + 
  geom_line(linewidth=0.5) + theme_bw(base_size=7)  + scale_colour_manual(values = pal) + xlim(c(0.1,1)) +
  facet_wrap(~NAME, ncol=4) + labs(color='Minimum GP') + ylab("Number Heterozygous + Homozygous alternative imputed sites") 
dev.off()


# ----------------------------------------------------------
# Create a figure comparing post-imputation and pre-imputation data (downsampled 0.5X vs imputed 0.5X)
# This figure is part of OSF (https://doi.org/10.17605/osf.io/av4f9)

# Create a data frame from a file that has the number of genotypes of Homozygous reference, Heterozygous, Homozygous alternative 
# and the total for downsampled diploid calls of 0.5X (created on the downsample 0.5X BAMs with the variant_calling_filtering.sh script 
# NOTE get genotype counts on the unfiltered VCF
# and the imputed 0.5X sample both for a MAF threshold of 5%
comparison_post_pre <- read.table("comparison_post_pre_imputation_0.5x_MAF_0.05_GP99.txt", header=TRUE, sep="\t", stringsAsFactors=TRUE)

# Ensure SAMPLE is in the correct order
comparison_post_pre$SAMPLE <- factor(data$SAMPLE, levels = c("Total","Homozygous reference", "Heterozygous", "Homozygous alternative"))

# Plot using ggplot2
pdf("comparison_post_pre_imputation_0.5x_MAF_0.05_GP99.pdf",width = 9, height = 8)
ggplot(comparison_post_pre, aes(x=NAME, y=N, fill=Status)) +
  geom_bar(stat="identity", position=position_dodge(width=0.65), width=0.6) + 
  facet_wrap(~ SAMPLE, scales = "free_y") +  
  scale_fill_manual(values = c("0.5X Imputed" = "#911EB4", "0.5X Downsampled" = "#E6BEFF")) + 
  theme_bw() +
  labs(x="", y="Number of sites", fill="") +
  theme(axis.text.x = element_text(angle=45, hjust=1)) 
dev.off()
